### ISSUE TITLE
Support for Fastboot 1.0.0rc6+

### ISSUE THREAD

**Issue by jurecuhalev** [kuzzmi/ember-cli-webfontloader#13]
Currently this addon doesn't work with new Fastboot as it changed the way the loading/detection is working:

https://github.com/ember-fastboot/ember-cli-fastboot/#build-hooks-for-fastboot
https://gist.github.com/kratiahuja/d22de0fb1660cf0ef58f07a6bcbf1a1c

**Comment by kuzzmi** [comment]
Thanks @gandalfar for providing the links. I haven't used Ember for a while, so it might take a bit of time for me to fix.

**Comment by jurecuhalev** [comment]
I'll give a try at making a PR.

Would you be open to a PR that moves webfontloader.js into external dependency, as opposed to minified file being included in the `vendor/` folder?

**Comment by kuzzmi** [comment]
That would be awesome! If this assures that `webfontloader` is used of a fixed version, then sure. They had a bad semver history, don't want to get into same troubles again.
