### ISSUE TITLE
ES6 syntax breaks build on CI server

### ISSUE THREAD

**Issue by balinterdi** [kuzzmi/ember-cli-webfontloader#3]
After having installed ember-cli-webfontloader in our app, the CI build breaks on the following line in the addon:

```
Unexpected token (
.../node_modules/ember-cli-webfontloader/index.js:7
included(app) {
^
```

I checked that `ember-cli-webfontloader` has `ember-cli-babel` as a dependency so I'm not sure if this is a problem in `ember-cli-webfontloader` itself but after a 5-min research I haven't seen another Ember addon that uses the ES6 syntax in its `index.js` so I'm not sure. FWIW, the tests pass locally.

**Comment by kuzzmi** [comment]
What CI system are you using? I'd prefer to not workaround an issue, but to find a real cause. For now, I guess, it would be wise to merge your pull request and move forward without ES6 in `index.js`, but generally that would be awesome to get more details.

**Comment by balinterdi** [comment]
We use [CodeShip](https://codeship.com).

**Comment by lolmaus** [comment]
@balinterdi Just tell Codeship to use Node 6.

**Comment by kuzzmi** [comment]
Thanks, @lolmaus. As there is a solution for this, I close an issue.

**Comment by balinterdi** [comment]
@lolmaus @kuzzmi Thank you, guys.

I updated node to version 5.12.0 on Codeship and it now works with the ES6 function syntax in `index.js` that [my PR](https://github.com/kuzzmi/ember-cli-webfontloader/pull/4) has reverted a while ago. Should I create a new PR that restores the ES6 syntax in `index.js`?

**Comment by kuzzmi** [comment]
Yes, please, that would be awesome!

**Comment by balinterdi** [comment]
Done: https://github.com/kuzzmi/ember-cli-webfontloader/pull/8
