### ISSUE TITLE
Missing `index.js` file

### ISSUE THREAD

**Issue by bobisjan** [kuzzmi/ember-cli-webfontloader#7]
Hi,

not sure if I broke something with FastBoot compatibility, but installing `v0.3.0` results in missing `index.js` in root directory.

Thanks!

**Comment by kuzzmi** [comment]
This is indeed something weird. 
I'll take a look ASAP, but any help will be much appreciated.

**Comment by bobisjan** [comment]
May be it's related to this, you can try npm pack with fixed version of npm https://github.com/npm/npm/issues/5082#issuecomment-226919433.

**Comment by kuzzmi** [comment]
I had v3.10.1 which was mentioned in the https://github.com/npm/npm/issues/5082#issuecomment-226919433 . However only updating npm to v3.10.6 fixed the issue. 

Please check now

**Comment by bobisjan** [comment]
Thanks! Will try today ASAP I get to computer.

**Comment by bobisjan** [comment]
@kuzzmi can confirm through our CI that `0.3.1` contains `index.js` 🎉.
